/*
 MIT
 MIT
 MIT
*/
var Canvas2D=function(){var a=this;this.container=document.createElement("div");this.canvas=document.createElement("canvas");this.canvas.style.width="100vw";this.canvas.style.height="100vh";this.canvas.style.position="absolute";this.container.style.margin="0%";this.container.style.width="100vw";this.container.style.height="100vh";this.container.style.position="relative";this.context=this.canvas.getContext("2d");this.container.appendChild(this.canvas);document.body.appendChild(this.container);this.rect=
this.canvas.getBoundingClientRect();$(window).on("resize",function(b){a.rect=a.canvas.getBoundingClientRect();a.canvas.width=a.rect.width;a.canvas.height=a.rect.height;a.width=a.rect.width;a.height=a.rect.height;a.buffer=a.context.createImageData(a.width,a.height)});this.canvas.width=this.rect.width;this.canvas.height=this.rect.height;this.width=this.rect.width;this.height=this.rect.height;this.pixelImageData=this.context.createImageData(1,1);this.buffer=this.context.createImageData(this.width,this.height)};
Canvas2D.prototype.drawPixel=function(a){this.pixelImageData.data[0]=a.r;this.pixelImageData.data[1]=a.g;this.pixelImageData.data[2]=a.b;this.pixelImageData.data[3]=a.a;this.context.putImageData(this.pixelImageData,a.x,a.y)};Canvas2D.prototype.drawBufferedPixel=function(a){var b=4*(a.x+a.y*this.width)-4;this.buffer.data[b]=a.r;this.buffer.data[b+1]=a.g;this.buffer.data[b+2]=a.b;this.buffer.data[b+3]=a.a};Canvas2D.prototype.flushBuffer=function(){this.context.putImageData(this.buffer,0,0)};
Canvas2D.prototype.clearBuffer=function(){this.buffer=this.context.createImageData(this.width,this.height)};Canvas2D.prototype.drawLine=function(a){this.context.beginPath();this.context.moveTo(a.x1,a.y1);this.context.lineTo(a.x2,a.y2);this.context.stroke()};
var Mandelbrot=function(a){var b=this;this.canvas2d=a;this.iterations=256;this.superscaling=this.scale=1;this.cY=this.cX=this.yDelta=this.xDelta=0;this.parallelism=2;this.shaderModes={BLUE:0,WHITE:1,HIST:2,INTHIST:3};this.shader=this.defaultShader=this.shaderModes.WHITE;$(this.canvas2d.canvas).on("click",function(a){return b._click(a)})};
Mandelbrot.prototype._click=function(a){this.xDelta+=(this.width/2-a.clientX)/this.scale;this.yDelta+=(this.height/2-a.clientY)/this.scale;this.scale*=2;console.log(a.clientX,a.clientY,this.cX,this.cY,this.xDelta,this.yDelta,this.scale);this.render()};
Mandelbrot.prototype.render=function(){if(window.Worker){this.canvas2d.clearBuffer();var a=this.scale,b=this.width=this.canvas2d.width,c=this.height=this.canvas2d.height;this.cX=this.width/2;this.cY=this.height/2;for(var d=this.xDelta,g=this.yDelta,f=this.parallelism,n=[],h={},e=0;e<f;h={$jscomp$this:h.$jscomp$this},e++)h.$jscomp$this=this,n[e]=new SyntheticWorker(this._baseRender,function(a){return function(c){c.data.line.map(function(a){return function(b,d){a.$jscomp$this.canvas2d.drawBufferedPixel(a.$jscomp$this._pixelShader(c.data.Px,
d,b,a.$jscomp$this.shader))}}(a));(1>=c.data.Px%(b/100)||c.data.Px>b-f-1)&&a.$jscomp$this.canvas2d.flushBuffer();c.data.Px>=b-(f-e)&&n[e].terminate()}}(h)),n[e].postMessage({iterations:this.iterations,scale:a,width:b,height:c,xDelta:d,yDelta:g,xSkip:f,xInit:e})}else this.renderDirect()};
Mandelbrot.prototype.renderDirect=function(){var a=this;this.canvas2d.clearBuffer();this.width=this.canvas2d.width;this.height=this.canvas2d.height;conf={data:{iterations:this.iterations,scale:this.scale,width:this.width,height:this.height,xDelta:this.xDelta,yDelta:this.yDelta,xSkip:1,xInit:0}};var b=(new Date).getTime();this._baseRender(conf,function(c){c.line.map(function(b,g){a.canvas2d.drawBufferedPixel(a._pixelShader(c.Px,g,b,a.shader))});50<(new Date).getTime()-b&&(b=(new Date).getTime(),setTimeout(function(){a.canvas2d.flushBuffer()},
50))})};Mandelbrot.prototype._baseRender=function(a,b){for(var c=a.data.iterations,d=a.data.scale,g=a.data.width,f=a.data.height,n=a.data.xDelta,h=a.data.yDelta,e=a.data.xSkip,k=a.data.xInit,p=3.5,q=p*f/g,p=p/d,q=q/d;k<g;k+=e){for(var t=[],u=0;u<f;u++){for(var v=p/g*(k-n*d)-p/1.4,w=q/f*(u-h*d)-q/2,l=0,m=0,r=0;4>l*l+m*m&&r<c;){var x=l*l-m*m+v,m=2*l*m+w,l=x;r++}t.push((r==c?0:r)/c)}b?b({Px:k,line:t}):postMessage({Px:k,line:t})}};
Mandelbrot.prototype._pixelShader=function(a,b,c,d){switch(d){case this.shaderModes.BLUE:return{x:a,y:b,r:51*c,g:127.5*c,b:255*c,a:255};case this.shaderModes.WHITE:return{x:a,y:b,r:255*c,g:255*c,b:255*c,a:255};case this.shaderModes.HIST:break;case this.shaderModes.INTHIST:break;default:return this._pixelShader(a,b,intentisty,this.shaderModes.BLUE)}};
var SyntheticWorker=function(a,b){var c=new Blob(["(function(global) { global.addEventListener('message', function(e) {","var cb = ",a.toString(),";","cb(e)","}, false); } )(this)"],{type:"application/javascript"});this.blobURL=URL.createObjectURL(c);this.worker=new Worker(this.blobURL);this.worker.onmessage=function(a){a.data.term?worker.terminate():b&&b(a)}};SyntheticWorker.prototype.terminate=function(){this.worker&&(this.worker.terminate(),URL.revokeObjectURL(this.blobURL))};
SyntheticWorker.prototype.postMessage=function(a){this.worker&&this.worker.postMessage(a)};(function(){window.canvas2D=new Canvas2D;$(window).on("load",function(){mandelbrot=new Mandelbrot(window.canvas2D);mandelbrot.render();var a=0;$(window).on("resize",function(){1E3<(new Date).getTime()-a&&(a=(new Date).getTime(),mandelbrot.render())})})})();
