/*
 MIT
 MIT
 MIT
*/
var Canvas2D=function(a){var b=this;this.container=document.createElement("div");this.canvas=document.createElement("canvas");this.canvas.style.width="100vw";this.canvas.style.height="100vh";this.canvas.style.position="absolute";this.container.style.margin="0%";this.container.style.width="100vw";this.container.style.height="100vh";this.container.style.position="relative";this.context=this.canvas.getContext("2d");this.container.appendChild(this.canvas);this.supersampling=1;a&&a.supersampling&&(this.supersampling=
a.supersampling);document.body.appendChild(this.container);this.rect=this.canvas.getBoundingClientRect();$(window).on("resize",function(a){b.rect=b.canvas.getBoundingClientRect();b.canvas.width=b.rect.width;b.canvas.height=b.rect.height;b.width=b.rect.width;b.height=b.rect.height;b.buffer=b.context.createImageData(b.width*b.supersampling,b.height*b.supersampling);b.resizeCB&&b.resizeCB()});this.canvas.width=this.rect.width;this.canvas.height=this.rect.height;this.width=this.rect.width;this.height=
this.rect.height;this.pixelImageData=this.context.createImageData(1,1);this.buffer=this.context.createImageData(this.width,this.height)};Canvas2D.prototype.setSupersampling=function(a){this.supersampling=a;this.rect=this.canvas.getBoundingClientRect();this.canvas.width=this.rect.width;this.canvas.height=this.rect.height;this.width=this.rect.width;this.height=this.rect.height;this.buffer=this.context.createImageData(this.width*this.supersampling,this.height*this.supersampling);return this};
Canvas2D.prototype.getWidth=function(){return this.width*this.supersampling};Canvas2D.prototype.getHeight=function(){return this.height*this.supersampling};Canvas2D.prototype.drawPixel=function(a){this.pixelImageData.data[0]=a.r;this.pixelImageData.data[1]=a.g;this.pixelImageData.data[2]=a.b;this.pixelImageData.data[3]=a.a;this.context.putImageData(this.pixelImageData,a.x,a.y)};
Canvas2D.prototype.drawBufferedPixel=function(a){var b=4*(a.x+a.y*this.width*this.supersampling)-4;this.buffer.data[b]=a.r;this.buffer.data[b+1]=a.g;this.buffer.data[b+2]=a.b;this.buffer.data[b+3]=a.a};Canvas2D.prototype.flushBuffer=function(){1<this.supersampling?this.context.putImageData(this.buffer,0,0,0,0,this.width,this.height):this.context.putImageData(this.buffer,0,0)};Canvas2D.prototype.clearBuffer=function(){this.buffer=this.context.createImageData(this.width,this.height)};
Canvas2D.prototype.drawLine=function(a){this.context.beginPath();this.context.moveTo(a.x1,a.y1);this.context.lineTo(a.x2,a.y2);this.context.stroke()};
var Mandelbrot=function(a){var b=this;this.iterations=512;this.supersampling=this.scale=1;this.yDelta=this.xDelta=0;this.parallelism=2;this.heightScalar=null;this.canvas2d=a.setSupersampling(this.supersampling);this.shaderModes={BLUE:0,WHITE:1,HIST:2,INTHIST:3};this.shader=this.defaultShader=this.shaderModes.BLUE;this.renderParallel=!0;this.renderTerm=!1;this.renderThreads=[];$(this.canvas2d.canvas).on("mousedown",function(a){return b._mousedown(a)});$(this.canvas2d.canvas).on("mouseup",function(a){return b._mouseup(a)})};
Mandelbrot.prototype.render=function(){if(this.width!=this.canvas2d.getWidth()||this.height!=this.canvas2d.getHeight())this.width=this.canvas2d.getWidth(),this.height=this.canvas2d.getHeight();var a={heightScalar:this.heightScalar,iterations:this.iterations,scale:this.scale,width:this.width,height:this.height,xDelta:this.xDelta,yDelta:this.yDelta,xSkip:this.parallelism};this.canvas2d.clearBuffer();window.Worker&&this.renderParallel?this._renderWorkers(a):this._renderDirect(a)};
Mandelbrot.prototype._renderWorkers=function(a){for(var b=a.xSkip,c=a.width;0<this.renderThreads.length;)this.renderThreads.pop().terminate();for(var d={},e=0;e<b;d={$jscomp$this:d.$jscomp$this},e++)d.$jscomp$this=this,this.renderThreads[e]=new SyntheticWorker(this._baseRender,function(a){return function(d){d.data.line.map(function(a){return function(b,c){a.$jscomp$this.canvas2d.drawBufferedPixel(a.$jscomp$this._pixelShader(d.data.Px,c,b,a.$jscomp$this.shader))}}(a));a.$jscomp$this.heightScalar=d.data.heightScalar;
(1>=d.data.Px%(c*b/100)||d.data.Px>c-b-1)&&a.$jscomp$this.canvas2d.flushBuffer();d.data.Px>=c-(b-e)&&a.$jscomp$this.renderThreads[e].terminate()}}(d)),a.xInit=e,this.renderThreads[e].postMessage(a)};
Mandelbrot.prototype._renderDirect=function(a){var b=this;a.xSkip=1;a.xInit=0;a={data:a};var c=(new Date).getTime();this._baseRender(a,function(a){a.line.map(function(c,k){b.canvas2d.drawBufferedPixel(b._pixelShader(a.Px,k,c,b.shader))});b.heightScalar=a.heightScalar;50<(new Date).getTime()-c&&(c=(new Date).getTime(),setTimeout(function(){b.canvas2d.flushBuffer()},50))})};
Mandelbrot.prototype._baseRender=function(a,b){for(var c=a.data.iterations,d=a.data.scale,e=a.data.width,k=a.data.height,q=3.5/d,m=3.5*k/e/d,f=a.data.xInit;f<e;f+=a.data.xSkip){for(var n=[],p=0;p<k;p++){for(var r=q/e*(f-a.data.xDelta*d)-q/1.4,t=m/k*(p-a.data.yDelta*d)-m/2,g=0,h=0,l=0;4>g*g+h*h&&l<c;){var u=g*g-h*h+r,h=2*g*h+t,g=u;l++}n.push((l==c?0:l)/c)}b?b({Px:f,line:n}):postMessage({Px:f,line:n,heightScalar:m})}};
Mandelbrot.prototype._pixelShader=function(a,b,c,d){switch(d){case this.shaderModes.BLUE:return d=c*(-.25*Math.log(-1/11.112347*c+.09)-.25),{x:a,y:b,r:255*d,g:255*d,b:255*c*(1-2.4*Math.log(c+1E-10)),a:255};case this.shaderModes.WHITE:return{x:a,y:b,r:255*c,g:255*c,b:255*c,a:255};case this.shaderModes.HIST:break;case this.shaderModes.INTHIST:break;default:return this._pixelShader(a,b,intentisty,this.defaultShader)}};
Mandelbrot.prototype._mousedown=function(a){1==a.buttons&&(this._mouseStartX=a.clientX,this._mouseStartY=a.clientY)};Mandelbrot.prototype._mouseup=function(a){2<a.clientX-this._mouseStartX||2<a.clientY-this._mouseStartY?(console.log("Translate"),this.xDelta+=(a.clientX-this._mouseStartX)/this.scale,this.yDelta+=(a.clientY-this._mouseStartY)/this.scale):(console.log("Zoom to mouse"),this.xDelta+=(this.width/2-a.clientX)/this.scale,this.yDelta+=(this.height/2-a.clientY)/this.scale,this.scale*=2);this.render()};
var SyntheticWorker=function(a,b){var c=a.toString();0==c.indexOf("function")&&(c=c.replace("function",""));0<=c.indexOf("prototype.")&&(c=c.replace("prototype.",""));c=new Blob(["(function(global) { global.addEventListener('message', function(e) {","var cb = function ",c,";","cb(e)","}, false); } )(this)"],{type:"application/javascript"});this.blobURL=URL.createObjectURL(c);this.worker=new Worker(this.blobURL);this.worker.onmessage=function(a){a.data.term?worker.terminate():b&&b(a)}};
SyntheticWorker.prototype.terminate=function(){this.worker&&(this.worker.terminate(),URL.revokeObjectURL(this.blobURL))};SyntheticWorker.prototype.postMessage=function(a){this.worker&&this.worker.postMessage(a)};(function(){window.canvas2D=new Canvas2D;$(window).on("load",function(){var a=new Mandelbrot(window.canvas2D);a.render();var b=0;canvas2D.resizeCB=function(){1E3<(new Date).getTime()-b&&(b=(new Date).getTime(),a.render())}})})();
