/*
 MIT
 MIT
*/
var Canvas2D=function(){var a=this;this.container=document.createElement("div");this.canvas=document.createElement("canvas");this.canvas.style.width="100vw";this.canvas.style.height="100vh";this.canvas.style.position="absolute";this.container.style.margin="0%";this.container.style.width="100vw";this.container.style.height="100vh";this.container.style.position="relative";this.context=this.canvas.getContext("2d");this.container.appendChild(this.canvas);document.body.appendChild(this.container);this.rect=
this.canvas.getBoundingClientRect();$(window).on("resize",(b)=>{a.rect=a.canvas.getBoundingClientRect();a.canvas.width=a.rect.width;a.canvas.height=a.rect.height;a.width=a.rect.width;a.height=a.rect.height;a.buffer=a.context.createImageData(a.width,a.height)});this.canvas.width=this.rect.width;this.canvas.height=this.rect.height;this.width=this.rect.width;this.height=this.rect.height;this.pixelImageData=this.context.createImageData(1,1);this.buffer=this.context.createImageData(this.width,this.height)};
Canvas2D.prototype.drawPixel=function(a){this.pixelImageData.data[0]=a.r;this.pixelImageData.data[1]=a.g;this.pixelImageData.data[2]=a.b;this.pixelImageData.data[3]=a.a;this.context.putImageData(this.pixelImageData,a.x,a.y)};Canvas2D.prototype.drawBufferedPixel=function(a){var b=4*(a.x+a.y*this.width)-4;this.buffer.data[b]=a.r;this.buffer.data[b+1]=a.g;this.buffer.data[b+2]=a.b;this.buffer.data[b+3]=a.a};Canvas2D.prototype.flushBuffer=function(){this.context.putImageData(this.buffer,0,0)};
Canvas2D.prototype.clearBuffer=function(){this.buffer=this.context.createImageData(this.width,this.height)};Canvas2D.prototype.drawLine=function(a){this.context.beginPath();this.context.moveTo(a.x1,a.y1);this.context.lineTo(a.x2,a.y2);this.context.stroke()};var Mandelbrot=function(a){var b=this;this.canvas2d=a;this.iterations=255;this.scale=1;this.cY=this.cX=this.yDelta=this.xDelta=0;this.parallelism=8;$(this.canvas2d.canvas).on("click",(a)=>b.click(a))};
Mandelbrot.prototype.click=function(a){this.xDelta+=(this.width/2-a.clientX)/this.scale;this.yDelta+=(this.height/2-a.clientY)/this.scale;this.scale*=2;console.log(a.clientX,a.clientY,this.cX,this.cY,this.xDelta,this.yDelta,this.scale);this.render()};
Mandelbrot.prototype.render=function(){if(window.Worker){this.canvas2d.clearBuffer();var a=this.scale,b=this.width=this.canvas2d.width,e=this.height=this.canvas2d.height;this.cX=this.width/2;this.cY=this.height/2;var k=this.xDelta,q=this.yDelta,f=this.parallelism,d=[];console.log(f);for(var c=0;c<f;c++)d[c]=new Worker("./js/mandelbrot-worker.js"),d[c].postMessage({iterations:this.iterations,scale:a,width:b,height:e,xDelta:k,yDelta:q,xSkip:f,xInit:c}),d[c].onmessage=function(a){var e=this;a.data.line.map((b,
c)=>{e.canvas2d.drawBufferedPixel({x:a.data.Px,y:c,r:51*b,g:127.5*b,b:255*b,a:255})});this.canvas2d.flushBuffer();a.data.Px>=b-(f-c)&&d[c].terminate()}.bind(this)}else this.renderDirect()};
Mandelbrot.prototype.renderDirect=function(){var a=this;this.canvas2d.clearBuffer();var b=this.scale,e=this.width=this.canvas2d.width,k=this.height=this.canvas2d.height;this.cX=this.width/2;this.cY=this.height/2;var q=this.xDelta,f=this.yDelta,d=3.5,c=d*k/e,d=d/this.scale,c=c/this.scale;setTimeout(()=>{var l=0,r=setInterval(()=>{for(var n=0;n<k;n++){for(var m=d/e*(l-q*b)-d/1.4,t=c/k*(n-f*b)-c/2,g=0,h=0,p=0;4>g*g+h*h&&p<a.iterations;){var u=g*g-h*h+m,h=2*g*h+t,g=u;p++}m=(255==p?0:p)/255;a.canvas2d.drawBufferedPixel({x:l,
y:n,r:51*m,g:127.5*m,b:255*m,a:255})}a.canvas2d.flushBuffer();l+=1;l>=e&&clearInterval(r)},0)},10)};(()=>{window.canvas2D=new Canvas2D;$(window).on("load",()=>{mandelbrot=new Mandelbrot(window.canvas2D);mandelbrot.render();var a=0;$(window).on("resize",()=>{1E3<(new Date).getTime()-a&&(a=(new Date).getTime(),mandelbrot.render())})})})();
